lr: 2e-5
train_batch_size: 16
eval_batch_size: 16
epochs: 10
weight_decay: 0.01


hydra:
  run:
    dir: .
  environment:
    USE_WANDB: true # set this to true and provide WANDB_API_KEY if you want to use wandb
    WANDB_API_KEY: ${oc.env:WANDB_API_KEY} # reference the API key from environment variable