name: CI-tests

on:
  push:

jobs:
  run-tests:
    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11"]

    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/setup-python@v5

      - name: Install ruff
        run: pip install ruff

      - name: Run pytest!
        run: ruff check
