name: Python package

on: [push]

jobs:
  run-tests:
    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11"]

    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Python and dependency setup
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: '**/requirements-dev.txt'
      - run: pip install -r requirements-dev.txt

      # - name: Install requirements.txt
      #   run: pip install -r requirements.txt

      # - name: Install requirements_dev.txt
      #   run: pip install -r requirements_dev.txt

      - name: Run pytest!
        run: pytest tests/


      # - name: Install dependencies
      #   run: python -m pip install pytest .

      # # You can test your matrix by printing the current Python version
      # - name: Display Python version
      #   run: python -c "import sys; print(sys.version)"