name: CI (pytests)

on:
  push:

jobs:
  run-tests:
    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11"]

    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache and python setup
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: '**/requirements_dev.txt'

      - name: Set USE_WANDB environment variable to false
        run: echo "USE_WANDB=false" >> $GITHUB_ENV

      - name: Install requirements_dev
        run: pip install -r requirements_dev.txt

      - name: Runing pytest
        run: pytest tests/
